services:
  server:
    build:
      dockerfile: Dockerfile
      target: build
    environment:
      - APP_VERSION=0.1.0-local
    working_dir: /laraorld
    volumes:
      - "./:/laralord"
    entrypoint: sh

  alpine:
    build:
      dockerfile: deploy/alpine/Dockerfile
      target: build
      context: .
