on:
  pull_request:
    branches:
      - main
name: Tests

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: inotify,apcu,sysvmsg,pcntl,openswoole,redis
          tools: composer, phpunit

      - name: Install Composer Dependencies
        run: composer install && composer bin box install

      - name: run-test
        run: phpunit

      - name: build
        run: |
          echo "Building PHAR: $APP_VERSION"
          ./vendor/bin/box compile  --no-parallel
        env:
          APP_VERSION: test-build-${{ github.ref }}
